### ISSUE TITLE
JavaScript（TypeScript）に Linter を導入する

### ISSUE THREAD

**Issue by piro0919** [softorwhite/react-blog#5]
**Is your feature request related to a problem? Please describe.**
Next.js デフォルトの ESLint の設定だけでは非常に弱く、保守性が低い。

**Describe the solution you'd like**
[eslint-config-standard](https://github.com/standard/eslint-config-standard) など、設定を追加する。

**Describe alternatives you've considered**

- [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb)
- [eslint-config-google](https://www.npmjs.com/package/eslint-config-google)

上記以外にも様々なルールセットが存在するため、選択は特に問いません。

**Comment by softorwhite** [comment]
@piro0919 
[eslint-config-standard](https://github.com/standard/eslint-config-standard#:~:text=This%20module%20is%20for%20advanced%20users.)に
>This module is for advanced users

と書いてあったので`.eslintrc`が要らない[standard](https://standardjs.com)にしようと思ったのですがこれだと弱いんでしょうか？

**Comment by piro0919** [comment]
@softorwhite 

逆に `standard` のほうは存在すら知りませんでした。 👀 
なので弱いか強いかすらちょっとわからないですね、申し訳ないです。 🙇 

試しに使用するのは全然アリだと思いますが、その場合既に入っている ESLint を削除して使用する感じですかね？

**Comment by softorwhite** [comment]
@piro0919 
ドキュメントをよんでみた感じ、standardはeslintがベースになっていてeslintとstandardが共存すると重複するので、eslintを削除するのが良さそうでした！他の`eslint-config-*`を使いたくなったときに切り変えるのでもいいかなと思いました。

**Comment by softorwhite** [comment]
@piro0919 と思ったのですが、prettierとのコンフリクトを避けるために[eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)を使えそうなのでやはりeslint-config-standardを使うようにしようと思いました！
